# A D D E R  
/gate/digitizer/Singles/insert adderCompton

# R E A D O U T  
/gate/digitizer/Singles/insert            readout  
/gate/digitizer/Singles/readout/setDepth  5

# E N E R G Y B L U R R I N G
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.23121
/gate/digitizer/Singles/blurring/setEnergyOfReference 200.0 keV

# E N E R G Y T H R E S H O L D 
/gate/digitizer/name                               HESingles 
/gate/digitizer/insert                             singleChain 
/gate/digitizer/HESingles/setInputName             Singles 
/gate/digitizer/HESingles/insert                   thresholder 
/gate/digitizer/HESingles/thresholder/setThreshold 200. keV 

# T I M E W I N D O W
/gate/digitizer/Coincidences/setWindow    4. ns 
/gate/digitizer/Coincidences/setInputName Singles 
/gate/digitizer/Coincidences/minSectorDifference 1
